# secret main file

# CMS specific



cric:
  # real CRIC
  real: true

  # URLs
  # TODO: CMS does not implement these endpoints, so we can for now keep these PanDA DOMA
  # there is also an option to define the content in an static 
  costMetrix: ""
  ddmBlackList: "https://datalake-cric.cern.ch/api/atlas/ddmendpointstatus/query/?json&activity=write_wan&fstate=OFF"
  ddmEndpoints: "https://datalake-cric.cern.ch/api/atlas/ddmendpoint/query/?json"
  schedConfig: "https://datalake-cric.cern.ch/api/atlas/pandaqueue/query/?json"
  sites: "https://datalake-cric.cern.ch/api/atlas/site/query/?json"
  objectStores: "https://datalake-cric.cern.ch/api/atlas/ddmendpoint/query/?json&state=ACTIVE&site_state=ACTIVE&preset=dict&json_pretty=1&type[]=OS_LOGS&type[]=OS_ES"

# TODO: no need to bother with these for now
object_store:
  host_name: "FIXME"
  port: 443
  bucket_name: "FIXME"
  access_key: "FIXME"
  secret_key: "FIXME"


proxy:
  httpProxy: ""
  httpsProxy: ""
